### ISSUE TITLE
 "Http" plugin is not implemented on ios

### ISSUE THREAD

**Issue by cldevel** [mymonero/mymonero-mobile#48]
### Description

iOS app It stopped working suddenly. During the launch, it shows: “ An unexpected application error occurred. The following error message was encountered: 

 "Http" plugin is not implemented on ios
Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148”

Reproducible 

### Steps to reproduce

Open the app with a configured wallet with history.

![E9BEFD0A-9F90-4CE3-BB22-5F6986B58D82](https://user-images.githubusercontent.com/63728315/178760299-1b8400c0-6aad-47d6-8305-a8db0f8a6e76.jpeg)

**Comment by cldevel** [comment]
After updating, it allows sending transactions, but shows a new error right after sending:

An unexpected application error occurred. The following error message was encountered:

 ```
null is not an object (evaluating ‘address.includes’)

Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
```

**Comment by karlbuys** [comment]
Hi @cldevel 

Thank you for letting us know

Our latest version has gone live via the Apple app store today, and it contains a fix for this issue. Please let me know if you experience any further issues
