### ISSUE TITLE
Unable to send Monero anywhere

### ISSUE THREAD

**Issue by techmelissa** [mymonero/mymonero-mobile#65]
On IOS I’m unable to send Monero to any wallet for any amount at any priority. Have uninstalled and reinstalled and this version is the updated one since the hard fork. I’ve read around that a lot of people are having same issue but I need some actual help and answers. Please advise if there’s a fix or if there’s something I can do with this IOS mobile app

**Comment by AslanPonies** [comment]
Hi @techmelissa,

MyMonero PSA

We are currently working on the latest Monero hardfork patch. 

The good news is that wallets are now scanning to their current block height where you are able to view your XMR. We are working on the decoy selection issue which relates to send transactions not confirming. 

We will update you on when the spending function is enabled.

**Comment by karlbuys** [comment]
Good day

Our latest release should have fixed the issue you were having. If you're still having difficulties, please re-open this thread
